allow excluding sectors from rendering
personality-insights/sunburst-chart pull request #7
Opened 2016-11-06 16:46 UTC by soumak77

resolves https://github.com/personality-insights/sunburst-chart/issues/2

2016-11-06 22:45 UTC, germanattanasio requested changes

2016-11-06 22:45 UTC, germanattanasio commented on src/personality-chart-renderer.js
> +    return -1 === exclude.findIndex(function (id) {
Can you use `indexOf` ? `findIndex` is not supported in IE.

```
return exclude.indexOf(child.id) === -1
```

2016-11-07 14:16 UTC, germanattanasio approved these changes

2016-11-07 14:16 UTC, merged

2016-11-07 14:16 UTC, germanattanasio commented
Thanks

2016-11-07 16:32 UTC, soumak77 commented
@germanattanasio this might actually be a breaking change as it currently sits.  The variable `profile` is assigned the object passed in from the caller, so by setting `profile.children`, the caller's object has now been modified.  I think the profile object will need to be copied so that it is not modified.